server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/150BigDream/SrpingCloundDemo.git
          searchPaths: config
          username: 150BigDream
          password: admin
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/